suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(lmerTest))
suppressPackageStartupMessages(library(emmeans))
src <- 'D:/Rprojects/research_data_synthesis/'
d <- read.csv(paste0(src,'April29_macro_max_mfa_no_gauss.csv'))
for (nm in c('dataset','has_y','tvae','approach','method')) d[[nm]] <- factor(d[[nm]])
d$y_synth <- factor(d$y_synth,levels=c('ctgan','tvae','categorical','pca_gmm','rf','xgb'))
d$appr_has_y <- factor(ifelse(d$approach=='old','old_appr_has_y',ifelse(d$has_y=='0','new_appr_no_y','new_appr_has_y')),levels=c('old_appr_has_y','new_appr_no_y','new_appr_has_y'))
cat('REPRODUCE SAVED MODEL\n')
f <- lmer(macro_max ~ appr_has_y + (1 | dataset + tvae),data=d,REML=FALSE)
print(formula(f)); print(VarCorr(f)); print(ngrps(f)); print(isSingular(f))
print(contrast(emmeans(f,~appr_has_y),method=list(new_hasY_vs_new_noY=c(0,-1,1),newApproach_vs_oldApproach=c(-1,.5,.5),hasY_vs_no_Y=c(1,-2,1)),adjust='tukey'))
cat('MODEL WITH Y_SYNTH INCLUDED\n')
fy <- lmer(macro_max ~ appr_has_y + (1 | tvae + dataset + y_synth),data=d,REML=FALSE)
print(VarCorr(fy)); print(contrast(emmeans(fy,~appr_has_y),list(new_vs_old=c(-1,.5,.5))))
cat('LINEAR MODEL CHECK AND HAS_Y SIGN\n')
fl <- lm(macro_max ~ y_synth*dataset + has_y + tvae,data=d)
print(contrast(emmeans(fl,~y_synth),list(old_vs_new=c(.5,.5,-.25,-.25,-.25,-.25))))
print(contrast(emmeans(fl,~has_y|tvae),list(noY_minus_hasY=c(1,-1))))
cat('DATASET-LEVEL DESCRIPTIVE CONTRASTS\n')
a <- aggregate(macro_max ~ dataset + approach,data=d,FUN=mean)
w <- reshape(a,idvar='dataset',timevar='approach',direction='wide')
w$delta <- w$macro_max.new-w$macro_max.old
print(w)
cat('SESSION\n');print(sessionInfo())
